package com.dante.calorietracker.core.ui.theme

import androidx.compose.ui.graphics.Color

internal val BrightGreen = Color(0xFF00C713)
val DarkGreen = Color(0xFF00790C)
val Orange = Color(0xFFFFAA00)
val CarbColor = Color(0xFFEEFF00)
val ProteinColor = Orange
val FatColor = Color(0xFFF44336)
val LightGray = Color(0xFF808080)
val MediumGray = Color(0xFF404040)
val DarkGray = Color(0xFF202020)
val TextWhite = Color(0xFFEEEEEE)

internal val DarkPrimary = Color(0xFF3de436)
internal val DarkOnPrimary = Color(0xFF003a01)
internal val DarkPrimaryContainer = Color(0xFF005303)
internal val DarkOnPrimaryContainer = Color(0xFF76ff65)
internal val DarkSecondary = Color(0xFFbbcbb2)
internal val DarkOnSecondary = Color(0xFF263422)
internal val DarkSecondaryContainer = Color(0xFF3c4b37)
internal val DarkOnSecondaryContainer = Color(0xFFd7e8cd)
internal val DarkTertiary = Color(0xFFffb952)
internal val DarkOnTertiary = Color(0xFF452b00)
internal val DarkTertiaryContainer = Color(0xFF633f00)
internal val DarkOnTertiaryContainer = Color(0xFFffddb4)
internal val DarkError = Color(0xFFffb4ab)
internal val DarkOnError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000a)
internal val DarkOnErrorContainer = Color(0xFFffdad6)
internal val DarkBackground = Color(0xFF001f25)
internal val DarkOnBackground = Color(0xFFa6eeff)
internal val DarkSurface = Color(0xFF001f25)
internal val DarkOnSurface = Color(0xFFa6eeff)
internal val DarkOutline = Color(0xFF8d9387)
internal val DarkSurfaceVariant = Color(0xFF43483f)
internal val DarkOnSurfaceVariant = Color(0xFFc3c8bc)

internal val LightPrimary = Color(0xFF006e05)
internal val LightOnPrimary = Color(0xFFffffff)
internal val LightPrimaryContainer = Color(0xFF76ff65)
internal val LightOnPrimaryContainer = Color(0xFF002200)
internal val LightSecondary = Color(0xFF53634e)
internal val LightOnSecondary = Color(0xFFffffff)
internal val LightSecondaryContainer = Color(0xFFd7e8cd)
internal val LightOnSecondaryContainer = Color(0xFF121f0e)
internal val LightTertiary = Color(0xFF825500)
internal val LightOnTertiary = Color(0xFFffffff)
internal val LightTertiaryContainer = Color(0xFFffddb4)
internal val LightOnTertiaryContainer = Color(0xFF291800)
internal val LightError = Color(0xFFba1a1a)
internal val LightOnError = Color(0xFFffffff)
internal val LightErrorContainer = Color(0xFFffdad6)
internal val LightOnErrorContainer = Color(0xFF410002)
internal val LightBackground = Color(0xFFf8fdff)
internal val LightOnBackground = Color(0xFF001f25)
internal val LightSurface = Color(0xFFf8fdff)
internal val LightOnSurface = Color(0xFF001f25)
internal val LightOutline = Color(0xFF73796e)
internal val LightSurfaceVariant = Color(0xFFdfe4d8)
internal val LightOnSurfaceVariant = Color(0xFF43483f)
